name: 'Install Dependencies'
description: 'Installs required dependencies for the build'
runs:
  using: "composite"
  steps:
    - name: Ensure sudo is installed
      shell: bash
      run: |
        if ! command -v sudo &>/dev/null; then
            apt-get update
            apt-get install -y sudo
        fi

    - name: Update and install dependencies
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y \
          lsb-release \
          coreutils \
          build-essential \
          libssl-dev \
          cmake \
          git \
          unzip \
          libicu-dev \
          curl \
          pkg-config \
          wget \
          \
          libsctp-dev \
          libc-dev \
          libatomic1 \
          clang \
          clang-format
